[versions]
grails-gradle-plugin = '6.2.0'
grails-gsp = '6.2.1'
grails-views = '3.2.3'
nexus-publish-gradle-plugin = '1.3.0'

[libraries]
grails-gradle-plugin = { module = 'org.grails:grails-gradle-plugin', version.ref = 'grails-gradle-plugin' }
grails-gsp-gradle-plugin = { module = 'org.grails.plugins:gsp', version.ref = 'grails-gsp' }
grails-views-gradle-plugin = { module = 'org.grails.plugins:views-gradle', version.ref = 'grails-views' }
nexus-publish-gradle-plugin = { module = 'io.github.gradle-nexus:publish-plugin', version.ref = 'nexus-publish-gradle-plugin' }
