[versions]
grails-gradle-plugin = '6.1.0'
grails-views = '3.1.0'
nexus-publish-gradle-plugin = '1.3.0'


[libraries]

#plugins
grails-gradle-plugin = { module = 'org.grails:grails-gradle-plugin', version.ref = 'grails-gradle-plugin' }
grails-views-gradle-plugin = { module = 'org.grails.plugins:views-gradle', version.ref = 'grails-views' }
nexus-publish-gradle-plugin = { module = 'io.github.gradle-nexus:publish-plugin', version.ref = 'nexus-publish-gradle-plugin' }
