[versions]
grails = '6.2.0'
grails-gsp = '6.2.1'
grails-testing-support = '3.2.2'
grails-views = '3.2.3'
micronaut = '4.7.4'
slf4j = '1.7.36'

[libraries]
grails-gsp = { module = 'org.grails.plugins:gsp', version.ref = 'grails-gsp' }
grails-interceptors = { module = 'org.grails:grails-plugin-interceptors', version.ref = 'grails' }
grails-testing-support-web = { module = 'org.grails:grails-web-testing-support', version.ref = 'grails-testing-support' }
grails-views-json = { module = 'org.grails.plugins:views-json', version.ref = 'grails-views' }
micronaut-inject-groovy = { module = 'io.micronaut:micronaut-inject-groovy', version.ref = 'micronaut' }
slf4j-nop = { module = 'org.slf4j:slf4j-nop', version.ref = 'slf4j' }
